# Dependencies
markdown:         kramdown
highlighter:      rogue
plugins:          [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            alp erkent
tagline:          'data scientist'
description:      'data scientist/analyst<br>medical doctor'
url:              https://alperkent.github.io/
baseurl:          /

author:
  name:           'Alp Erkent'
  url:            

paginate:         5

# Custom vars
version:          04/2023

resume:           https://alperkent.github.io/resume/
github:           https://github.com/alperkent/
kaggle:           https://www.kaggle.com/alperkent/
